name: CI
on:
  push:
    branches:
      - master

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with: 
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test
      - name: "Run Flutter Driver tests"
        run: "flutter drive --driver=test_driver/integration_driver.dart --target=integration_test/app_test.dart"
