name: CI Test App
on:
  push:
    branches:
      - master

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: macOS-latest
    if: false
    strategy:
      matrix:
        device:
          - "pixel_xl"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: '2.2.2'
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_SIGN_PWD: ${{ secrets.ANDROID_SIGN_PWD }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          api-level: 30
          profile: ${{ matrix.device }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            ./scripts/setenv.sh
            cd ./photochatapp
            flutter pub get
            flutter drive --driver=test_driver/integration_driver.dart --target=integration_test/app_test.dart

